export default [
  {
    __typename: "Transaction",
    amount: 1000,
    category: 12,
    currency: '{"id":1,"name":"USD","symbol":"$"}',
    date: 1612522218760,
    id: 1,
    income: false,
    title: "Bills",
  },
  {
    __typename: "Transaction",
    amount: 2000,
    category: 1,
    currency: '{"id":1,"name":"USD","symbol":"$"}',
    date: 1612282497000,
    id: 2,
    income: true,
    title: "Salary",
  },
  {
    __typename: "Transaction",
    amount: 1240,
    category: 5,
    currency: '{"id":4,"name":"EUR","symbol":"€"}',
    date: 1612132897000,
    id: 3,
    income: false,
    title: "University",
  },
  {
    __typename: "Transaction",
    amount: 1245000,
    category: 4,
    currency: '{"id":2,"name":"UAH","symbol":"₴"}',
    date: 1580669697000,
    id: 4,
    income: false,
    title: "Buying a house",
  },
  {
    __typename: "Transaction",
    amount: 1245,
    category: 2,
    currency: '{"id":4,"name":"EUR","symbol":"€"}',
    date: 1612411297000,
    id: 5,
    income: true,
    title: "Correction",
  },
  {
    __typename: "Transaction",
    amount: 124,
    category: 8,
    currency: '{"id":1,"name":"USD","symbol":"$"}',
    date: 1611312497000,
    id: 6,
    income: false,
    title: "Food",
  },
  {
    __typename: "Transaction",
    amount: 2000,
    category: 11,
    currency: '{"id":1,"name":"USD","symbol":"$"}',
    date: 1610727697000,
    id: 7,
    income: false,
    title: "Walmart",
  },
  {
    __typename: "Transaction",
    amount: 85,
    category: 6,
    currency: '{"id":3,"name":"RUB","symbol":"₽"}',
    date: 1612500497000,
    id: 8,
    income: false,
    title: "Spotify",
  },
  {
    __typename: "Transaction",
    amount: 5000,
    category: 1,
    currency: '{"id":3,"name":"RUB","symbol":"₽"}',
    date: 1610172273000,
    id: 9,
    income: true,
    title: "Salary",
  },
  {
    __typename: "Transaction",
    amount: 5000,
    category: 3,
    currency: '{"id":1,"name":"USD","symbol":"$"}',
    date: 1610115334000,
    id: 10,
    income: true,
    title: "Donation alerts",
  },
];
